// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWh1pbtP-77MERv-uHz96PQduPaXV_0Y',
    appId: '1:334479875027:web:b1c6e02c58dfe93f542d26',
    messagingSenderId: '334479875027',
    projectId: 'agrivision-bbe02',
    authDomain: 'agrivision-bbe02.firebaseapp.com',
    storageBucket: 'agrivision-bbe02.firebasestorage.app',
    measurementId: 'G-YQ0TZDNSGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8J67WqWvppxpNXE23EeL4Z9XWBmCu7mc',
    appId: '1:334479875027:android:19563a3ccf86fd62542d26',
    messagingSenderId: '334479875027',
    projectId: 'agrivision-bbe02',
    storageBucket: 'agrivision-bbe02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ2P8fBUdDVVxVyGjqTxPXOPE72Iy1BWs',
    appId: '1:334479875027:ios:092b42d5322659f9542d26',
    messagingSenderId: '334479875027',
    projectId: 'agrivision-bbe02',
    storageBucket: 'agrivision-bbe02.firebasestorage.app',
    iosBundleId: 'com.example.agrivision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ2P8fBUdDVVxVyGjqTxPXOPE72Iy1BWs',
    appId: '1:334479875027:ios:092b42d5322659f9542d26',
    messagingSenderId: '334479875027',
    projectId: 'agrivision-bbe02',
    storageBucket: 'agrivision-bbe02.firebasestorage.app',
    iosBundleId: 'com.example.agrivision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGWh1pbtP-77MERv-uHz96PQduPaXV_0Y',
    appId: '1:334479875027:web:1e793a4994b735c6542d26',
    messagingSenderId: '334479875027',
    projectId: 'agrivision-bbe02',
    authDomain: 'agrivision-bbe02.firebaseapp.com',
    storageBucket: 'agrivision-bbe02.firebasestorage.app',
    measurementId: 'G-W0DGGN81KH',
  );
}
